--- 
before_install: 
  - "docker build -t ubuntu/docker-react -f Dockerfile.dev ."
language: generic
script: 
  - "docker run -e CI=true ubuntu/docker-react npm run test"
service: 
  - docker
sudo: required

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "
  env: ""
  bucket_name: ""
  bucket_path: "Enter App name"
  on:
    branch: master


