--- 
before_install: 
  - "docker build -t ubuntu/docker-react -f Docekrfile.dev ."
language: generic
script: 
  - "docker run -e CI=true ubuntu/docker_react npm run test"
service: 
  - docker
sudo: required
